terminal:
  customColorSchemes:
    - name: Decay
      foreground: '#b6beca'
      background: '#101419'
      cursor: '#e2a6ff'
      colors:
        - '#1c252c'
        - '#e05f65'
        - '#78dba9'
        - '#f1cf8a'
        - '#70a5eb'
        - '#c68aee'
        - '#74bee9'
        - '#dee1e6'
        - '#384148'
        - '#e2a6ff'
        - '#1c252c'
        - '#384148'
        - '#8cc1ff'
        - '#b6beca'
        - '#ffeba6'
        - '#fafdff'
    - name: Decayce
      foreground: '#a5b6cf'
      background: '#0d0f18'
      cursor: '#c296eb'
      colors:
        - '#1c1e27'
        - '#dd6777'
        - '#90ceaa'
        - '#ecd3a0'
        - '#86aaec'
        - '#c296eb'
        - '#93cee9'
        - '#d0d3d8'
        - '#384148'
        - '#c79bf0'
        - '#1c1d27'
        - '#151720'
        - '#86aaec'
        - '#cbced3'
        - '#f1d8a5'
        - '#f7f7f7'
      cursorAccent: undefined
